### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by rinmehmeti** [aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4#7]
I'm getting this error with the provided sample console application.

I've tried to compile the program on different computers it worked, but for some reason, it's not working on mine. 

I turned off the firewall and I am not using any proxy. Still getting the same exception. Please help.

Target framework: .NET Core 2.2
OS: Windows 10 1809 17763.1098
IDE: Visual Studio 2017/2019

----------------------------------------------------------------------------------------------------------

2020-04-07 20:44:59,373 ERROR AwsIOTMqttOverWebsockets.Utils.Logger - Unable to connect to the remote server

Unhandled Exception: MQTTnet.Exceptions.MqttCommunicationException: Unable to connect to the remote server ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttWebSocketChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.TaskExtensions.TimeoutAfterAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options)
   at AwsIOTMqttOverWebsockets.Messaging.CloudConnector.ConnectToAwsIoT() in C:\Users\Admin\Documents\GitHub\aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4\Dotnet core console app\AwsIOTMqttOverWebsockets\AwsIOTMqttOverWebsockets\Messaging\CloudConnector.cs:line 46
   at AwsIOTMqttOverWebsockets.Program.Main(String[] args) in C:\Users\Admin\Documents\GitHub\aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4\Dotnet core console app\AwsIOTMqttOverWebsockets\AwsIOTMqttOverWebsockets\Program.cs:line 19
   at AwsIOTMqttOverWebsockets.Program.<Main>(String[] args)
Press any key to continue . . .

**Comment by dominikwantuch** [comment]
I was getting same error. It turned out that I was using wrong credentials. Right after login to AWS dashboard, there was option like "Command line or programmatic access" I followed it, and took credentials from there and then I was getting "Unable to connect to remote server". In order to get it working, go to IAM Service, create user with administrator rights and programmatic access, and take accesKey and secretKey from there. Probably too late to help you, but maybe it will help someone else in the future, cheers :)
